version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: asynctester-db
    environment:
      POSTGRES_DB: asynctester
      POSTGRES_USER: asynctester
      POSTGRES_PASSWORD: asynctester
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: asynctester-redis
    ports:
      - "6378:6379"

  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: asynctester-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka

  app:
    build: .
    image: asynctester-be
    container_name: asynctester-app
    depends_on:
      - postgres
      # - kafka
      - redis
    ports:
      - "9000:9000"
      - "8080:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/asynctester
      - POSTGRES_USER=asynctester
      - POSTGRES_PASSWORD=asynctester
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HOST=redis
      - PLAY_SECRET=adkfjalskdghalskdjghalskdjghalskdjghalskdjghalskdjgh
      - JWT_SECRET=developmentsercret
      - RUN_SERVER=true
      - RUN_WORKER=true
      - EMAIL_PASSWORD=changeme
      - EMAIL_PASSWORD_USERNAME="akshitbansal2828@gmail.com"
      - GOOGLE_CLIENT_ID=changeme

volumes:
  postgres_data:
  kafka_data:
